name: Flutter Build and Deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests (skip if no test directory)
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No test directory found, skipping tests"
          fi

      - name: Build APK
        run: flutter build apk --release
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          VISION_AUTH_TOKEN: ${{ secrets.VISION_AUTH_TOKEN }}
          VISION_BASE_URL: ${{ secrets.VISION_BASE_URL }}
          VISION_PROJECT_ID: ${{ secrets.VISION_PROJECT_ID }}
